config/routes.rb
Rails.application.routes.draw do

  post 'add_answer_option_ajax' => 'answer_options#add_answer_option_ajax'
  resources :answer_options

  post 'questions_by_survey' => 'questions#find_by_survey'
  get 'questions/:id/edit/:survey_id' => 'questions#edit'
  get 'questions/new/:survey_id' => 'questions#new'
  resources :questions

  get 'survey/:survey_id/send_notification' => 'courses#send_notification', as: 'send_notification'
  get 'results_by_group/:course_id/:survey_name/:group_name' => 'surveys#results_by_group', as: 'results_by_group'
  get 'results_by_user/:survey_id' => 'surveys#results_by_user', as: 'results_by_user'
  get 'my_surveys/:id/results/:course_id/:survey_name/:evaluated_user_id/:user_id' => 'surveys#results', as: 'survey_results'
  post 'save_survey_answers' => 'surveys#save_survey_answers'
  get 'survey/:id/answer' => 'surveys#answer_survey', as: 'answer_survey'
  get 'my_surveys/pending' => 'surveys#my_pending_surveys', as: 'my_pending_surveys'
  get 'my_surveys' => 'surveys#my_surveys'
  get 'surveys/:id/preview' => 'surveys#preview', as: 'survey_preview'
  resources :surveys
  
  post 'courses/check_students_list' => 'courses#check_students_list', as: 'check_students_list'
  get 'couses/:course_id/results/:survey_name/group/:group_name' => 'courses#survey_results_by_group', as: 'survey_group_results'
  post 'update_assigned_survey' => 'courses#update_assigned_survey'
  get 'courses/:course_id/edit_assigned_survey/:survey_id' => 'courses#edit_assigned_survey', as: 'edit_assigned_survey'
  get 'courses/:course_id/assigned_survey/:survey_name' => 'courses#assigned_survey_details', as: 'assigned_survey_details'
  post 'save_assigned_survey' => 'courses#save_assigned_survey'
  get 'course/:id/assign_survey' => 'courses#assign_survey', as: 'assign_survey'
  post 'assign_student_to_course' => 'courses#assign_student_to_course'
  post 'remove_student_from_course' => 'courses#remove_student_from_course'
  get 'courses/:id/assign_students' => 'courses#assign_students', as: 'assign_students'
  resources :courses
  
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit_user'
  patch 'users/:id/edit' => 'users#update_user'
  delete 'user/:id' => 'users#destroy'
  get 'new_user' => 'users#new_user'
  post 'users/create_user' => 'users#create_user'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  devise_for :users
  get 'dashboard/index'

   root 'dashboard#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answer_options

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_survey, only: [:new]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to survey_path(@question.survey), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to survey_path(@question.survey.id), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find_by_survey
    @questions = Question.where(survey_id: params[:survey_id])
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_survey
      @survey = Survey.find(params[:survey_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:statement, :hint, :score, :survey_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :statement, 'Enunciado' %><br>
    <%= f.text_field :statement, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :hint, 'Indicación' %><br>
    <%= f.text_field :hint, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :score, 'Puntaje' %><br>
    <%= f.number_field :score, min: 1, step: 1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :survey_id, value: params[:survey_id], class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-flat btn-primary btn-block' %>
<% end %>

app/views/questions/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Editar pregunta
    <small>Edite la pregunta o agregue opciones de respuesta</small>
  </h1>
  <ol class="breadcrumb">
  	<li><a href="<%= surveys_path %>">Encuestas</a></li>
  	<li><a href="<%= survey_path(@question.survey.id) %>"><%= @question.survey.name %></a></li>
  	<li class="active">Editar pregunta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
  	<div class="col-xs-12">
  		<%= link_to survey_path(@question.survey)  do %>
  			<i class="fa fa-arrow-left"></i> Volver
  		<% end %>
  	</div>
	</div>
	<div class="row">
		<br>
    <div class="col-xs-12 col-md-5">
    	<div class="box box-primary">
    		<div class="box-header with-border">
    			<h3 class="box-title">Editar pregunta</h3>
    		</div>
	    	<div class="box-body">
					<%= render 'form' %>
	    	</div>
    	</div>
    </div>
    <div class="col-xs-12 col-md-7">
    	<div class="box box-success">
    		<div class="box-header with-border">
    			<h3 class="box-title">Opciones de respuesta</h3>
					<div class="box-tools pull-right">
						<button class="btn btn-primary btn-flat" id="add-answer-btn"><i class="fa fa-plus"></i> Agregar opciones de respuesta</button>
					</div>
    		</div>
    		<div class="box-body">
    			<div id="new-answer" class="hidden">
    				<div class="box">
    					<div class="box-header with-border">
    						<h3 class="box-title">Agregar opción de respuesta</h3>
    						<div class="box-tools pull-right">
    							<i class="fa fa-times" id="close-new-answer"></i>
								</div>
    					</div>
    					<div class="box-body">
    						<div class="form-group">
							    <%= label_tag :answer, 'Respuesta' %><br>
							    <%= text_field_tag :answer, '', id: 'new-answer-def', class: 'form-control' %>
							  </div>
							  <div class="form-group">
							    <%= label_tag :score, 'Puntaje' %><br>
							    <%= number_field_tag :score, 1, min: 1, step: 1, id: 'new-answer-score', class: 'form-control' %>
							  </div>
						    <%= hidden_field_tag :question_id, @question.id, id: 'new-answer-question', class: 'form-control' %>
							  <button class="btn btn-primary btn-flat btn-block" id="new-answer-btn" disabled><i class="fa fa-plus"></i> Agregar</button>
    					</div>	
    				</div>
    			</div>
            <table class="table">
              <thead>
                <th>Opción de respuesta</th>
                <th>Puntaje</th>
                <th></th>
                <th></th>
              </thead>
              <tbody id="answer-options">
                <% unless @question.answer_options.empty? %>
    							<% @question.answer_options.each do |answer| %>
      							<tr>
  			    					<td><%= answer.answer %></td>
  			    					<td><%= answer.score %></td>
                      <td>
                        <a href="<%= edit_answer_option_path(answer) %>">
                          <i class="fa fa-pencil blue"></i>
                        </a>
                      </td>
                      <td>
                        <%= link_to answer, method: :delete, data: { confirm: '¿Está seguro(a) de que desea eliminar esta opción de respuesta?' } do %>
                          <i class="fa fa-times red"></i>
                        <% end %>
                      </td>
      							</tr>
                  <% end %>
          			<% else %>
          				<td id="answer-options-empty">Esta pregunta no tiene opciones de respuesta asignadas</td>
          			<% end %>
              </tbody>
            </table>
    		</div>
    	</div>
    </div>
  </div>
</section>
<!-- /.content -->

<script>
	var new_answer = $('#new-answer');
	$(document).ready(function(){
		new_answer.hide().removeClass('hidden');
	});
	
	$('#add-answer-btn').click(function(){
		new_answer.show(300);
	});

	$('#close-new-answer').click(function(){
		new_answer.hide(300);
	});

	$('#new-answer-def').blur(function(){
		if (this.value) {
			$('#new-answer-btn').removeAttr('disabled');
		}
	});

	$('#new-answer-btn').click(function(){
		$.post('<%= add_answer_option_ajax_path %>',
      {
        answer: $('#new-answer-def').val(),
        score: $('#new-answer-score').val(),
        question_id: $('#new-answer-question').val()
      })
      .done(function(data){            
      	clearForm();
      	data = JSON.parse(data);
        try{
          $('#answer-options-empty').remove();
        }
        catch(e){
          
        }
      	$('#answer-options').append(
      			'<tr>'+
							'<td>'+data.answer+'</td>'+
              '<td>'+data.score+'</td>'+
              '<td>'+
                '<a href="/answer_options/'+data.id+'/edit">'+
                  '<i class="fa fa-pencil blue"></i>'+
                '</a>'+
              '</td>'+
              '<td>'+
                '<a href="/answer_options/'+data.id+'" data-confirm="¿Está seguro(a) de que desea eliminar esta opción de respuesta?" rel="nofollow" data-method="delete">'+
                  '<i class="fa fa-times red"></i>'+
                '</a>'+
              '</td>'+
						'</tr>'
      		)
        toastr['info']('Opción de respuesta agregada con éxito');
      });
	});

	function clearForm(){
		$('#new-answer-def').val('');
		$('#new-answer-score').val(1);
		$('#new-answer-question').val();
		$('#new-answer-btn').attr('disabled', 'disabled');
		new_answer.hide();
	}
</script>

app/views/questions/find_by_survey.js.erb
$("<%= escape_javascript(render partial: 'surveys/questions', locals: {questions: @questions}) %>").appendTo("#survey-questions");

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Statement</th>
      <th>Hint</th>
      <th>Score</th>
      <th>Survey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.statement %></td>
        <td><%= question.hint %></td>
        <td><%= question.score %></td>
        <td><%= question.survey %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Agregar preguntas
    <small>Cree preguntas para la encuesta '<%= @survey.name %>'</small>
  </h1>
  <ol class="breadcrumb">
  	<li><a href="<%= surveys_path %>">Encuestas</a></li>
  	<li><a href="<%= survey_path(params[:survey_id]) %>"><%= @survey.name %></a></li>
    <li class="active">Agregar preguntas</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
  	<div class="col-xs-12">
  		<%= link_to surveys_path  do %>
  			<i class="fa fa-arrow-left"></i> Volver
  		<% end %>
  	</div>
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
					<%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /.content -->

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statement:</strong>
  <%= @question.statement %>
</p>

<p>
  <strong>Hint:</strong>
  <%= @question.hint %>
</p>

<p>
  <strong>Score:</strong>
  <%= @question.score %>
</p>

<p>
  <strong>Survey:</strong>
  <%= @question.survey %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>