config/routes.rb
Rails.application.routes.draw do

  post 'add_answer_option_ajax' => 'answer_options#add_answer_option_ajax'
  resources :answer_options

  post 'questions_by_survey' => 'questions#find_by_survey'
  get 'questions/:id/edit/:survey_id' => 'questions#edit'
  get 'questions/new/:survey_id' => 'questions#new'
  resources :questions

  get 'survey/:survey_id/send_notification' => 'courses#send_notification', as: 'send_notification'
  get 'results_by_group/:course_id/:survey_name/:group_name' => 'surveys#results_by_group', as: 'results_by_group'
  get 'results_by_user/:survey_id' => 'surveys#results_by_user', as: 'results_by_user'
  get 'my_surveys/:id/results/:course_id/:survey_name/:evaluated_user_id/:user_id' => 'surveys#results', as: 'survey_results'
  post 'save_survey_answers' => 'surveys#save_survey_answers'
  get 'survey/:id/answer' => 'surveys#answer_survey', as: 'answer_survey'
  get 'my_surveys/pending' => 'surveys#my_pending_surveys', as: 'my_pending_surveys'
  get 'my_surveys' => 'surveys#my_surveys'
  get 'surveys/:id/preview' => 'surveys#preview', as: 'survey_preview'
  resources :surveys
  
  post 'courses/check_students_list' => 'courses#check_students_list', as: 'check_students_list'
  get 'couses/:course_id/results/:survey_name/group/:group_name' => 'courses#survey_results_by_group', as: 'survey_group_results'
  post 'update_assigned_survey' => 'courses#update_assigned_survey'
  get 'courses/:course_id/edit_assigned_survey/:survey_id' => 'courses#edit_assigned_survey', as: 'edit_assigned_survey'
  get 'courses/:course_id/assigned_survey/:survey_name' => 'courses#assigned_survey_details', as: 'assigned_survey_details'
  post 'save_assigned_survey' => 'courses#save_assigned_survey'
  get 'course/:id/assign_survey' => 'courses#assign_survey', as: 'assign_survey'
  post 'assign_student_to_course' => 'courses#assign_student_to_course'
  post 'remove_student_from_course' => 'courses#remove_student_from_course'
  get 'courses/:id/assign_students' => 'courses#assign_students', as: 'assign_students'
  resources :courses
  
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit_user'
  patch 'users/:id/edit' => 'users#update_user'
  delete 'user/:id' => 'users#destroy'
  get 'new_user' => 'users#new_user'
  post 'users/create_user' => 'users#create_user'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  devise_for :users
  get 'dashboard/index'

   root 'dashboard#index'

end

app/views/layouts/shared/_control_sidebar.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane active" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="pull-right-container">
                <span class="label label-danger pull-right">70%</span>
              </span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
   immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

app/views/layouts/shared/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
	<!-- To the right -->
	<div class="pull-right hidden-xs">
	  Anything you want
	</div>
	<!-- Default to the left -->
	<strong>Copyright &copy; 2017 <a href="#" target="_blank">Manuel App</a>.</strong> All rights reserved.
</footer>

app/views/layouts/shared/_header.html.erb
<!-- Main Header -->
<header class="main-header">
	<!-- Logo -->
	<a href="<%= root_path %>" class="logo">
	  <!-- mini logo for sidebar mini 50x50 pixels -->
	  <span class="logo-mini">
	  	LOGO MANUEL
	  </span>
	  <!-- logo for regular state and mobile devices -->
	  <span class="logo-lg">
	  	LOGO MANUEL
	  </span>
	</a>

	<!-- Header Navbar -->
	<nav class="navbar navbar-static-top" role="navigation">
	  <!-- Sidebar toggle button-->
	  <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
	    <span class="sr-only">Toggle navigation</span>
	  </a>
	  <!-- Navbar Right Menu -->
	  <div class="navbar-custom-menu">
	    <ul class="nav navbar-nav">	         
	      <!-- User Account Menu -->
	      <li class="dropdown user user-menu">
	        <!-- Menu Toggle Button -->
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	          <!-- The user image in the navbar-->
	          <!--  <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->
	          <!-- hidden-xs hides the username on small devices so only the image appears. -->
	          <span class="hidden-xs"><%= current_user.full_name%></span>
	        </a>
	        <ul class="dropdown-menu">
	          <!-- The user image in the menu -->
	          <li class="user-header">
	            <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">-->

	            <p>
	              <%= current_user.full_name%> - <%= current_user.role%>
	              <small>Miembro desde <%= current_user.created_at%></small>
	            </p>
	          </li>
	          <!-- Menu Footer-->
	          <li class="user-footer">
	            <div class="pull-left">
	              <!-- <a href="#" class="btn btn-default btn-flat">Profile</a> -->
	            </div>
	            <div class="pull-right">
	            	<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
	            </div>
	          </li>
	        </ul>
	      </li>
	    </ul>
	  </div>
	</nav>
</header>

app/views/layouts/shared/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">

	  <!-- Sidebar user panel (optional) -->
	  <div class="user-panel">
	  </div>

	  <!-- Sidebar Menu -->
	  <ul class="sidebar-menu">
	    <li class="header">MENÚ</li>
	    <!-- Optionally, you can add icons to the links -->
      <% if current_user.admin? %>
		    <li class="treeview">
		      <a href="#"><i class="fa fa-user"></i> <span>Usuarios</span>
		        <span class="pull-right-container">
		          <i class="fa fa-angle-left pull-right"></i>
		        </span>
		      </a>
		      <ul class="treeview-menu">
		      	<% if can? :read, User %>
							<li><a href="<%= users_url %>"><i class="fa fa-list"></i> Todos los usuarios</a></li>
		      	<% end %>
		      	<% if can? :create, User %>
		        	<li><a href="<%= new_user_path %>"><i class="fa fa-plus"></i> Nuevo usuario</a></li>
		        <% end %>
		      </ul>
	    	</li>
      <% end %>
	    <li class="treeview">
	      <a href="#"><i class="fa fa-book"></i> <span>Cursos</span>
	        <span class="pull-right-container">
	          <i class="fa fa-angle-left pull-right"></i>
	        </span>
	      </a>
	      <% if current_user.admin? %>
		      <ul class="treeview-menu">
		      	<li><a href="<%= courses_path %>"><i class="fa fa-list"></i> Todos los cursos</a></li>
		      	<% if can? :create, Course %>
		        	<li><a href="<%= new_course_path %>"><i class="fa fa-plus"></i> Nuevo curso</a></li>
		        <% end %>
		      </ul>
	      <% else %>
	      	<ul class="treeview-menu">
		      	<li><a href="<%= courses_path %>"><i class="fa fa-list"></i> Mis cursos</a></li>
	        	<li><a href="#<%#= new_course_path %>"><i class="fa fa-chevron-circle-left"></i> Cursos antiguos</a></li>
		      </ul>
	      <% end %>	
	    </li>
	    <li class="treeview">
	      <a href="#"><i class="fa fa-check-square-o"></i> <span>Encuestas</span>
	        <span class="pull-right-container">
	          <i class="fa fa-angle-left pull-right"></i>
	        </span>
	      </a>
	      <% if current_user.admin? %>
		      <ul class="treeview-menu">
		      	<li><a href="<%= surveys_path %>"><i class="fa fa-list"></i> Todas las encuestas</a></li>
		      	<% if can? :create, Survey %>
		        	<li><a href="<%= new_survey_path %>"><i class="fa fa-plus"></i> Nueva encuesta</a></li>
		        <% end %>
	        	<li><a href="#<%#= new_survey_path %>"><i class="fa fa-pie-chart"></i> Resultados</a></li>
		      </ul>
	      <% elsif current_user.teacher? %>
		      <ul class="treeview-menu">
		      	<li><a href="<%= my_surveys_path %>"><i class="fa fa-list"></i> Encuestas activas</a></li>
	        	<li><a href="#<%#= new_survey_path %>"><i class="fa fa-chevron-circle-left"></i> Encuestas anteriores</a></li>
	        	<li><a href="#<%#= new_survey_path %>"><i class="fa fa-pie-chart"></i> Resultados</a></li>
		      </ul>
	      <% else %>
		      <ul class="treeview-menu">
	        	<li><a href="<%= my_surveys_path %>"><i class="fa fa-list"></i> Mis encuestas</a></li>
		      	<li>
		      		<a href="<%= my_pending_surveys_path %>"><i class="fa fa-exclamation-triangle"></i> Encuestas pendientes 
		      			<% if get_pending_surveys > 0 %>
			      			<span class="pull-right-container">
			      				<span class="label label-warning pull-right"><%= get_pending_surveys %></span>
			      			</span>
		      			<% end %>
	      			</a>
      			</li>
	        	<!-- <li><a href="#<%#= new_survey_path %>"><i class="fa fa-chevron-circle-left"></i> Encuestas anteriores</a></li> -->
		      </ul>
	      <% end %>
	    </li>
	  	<li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out"></i> <span>Cerrar Sesión</span><%end%></li>
	  
	  </ul>
	  <!-- /.sidebar-menu -->
	</section>
	<!-- /.sidebar -->
</aside>