config/routes.rb
Rails.application.routes.draw do

  post 'add_answer_option_ajax' => 'answer_options#add_answer_option_ajax'
  resources :answer_options

  post 'questions_by_survey' => 'questions#find_by_survey'
  get 'questions/:id/edit/:survey_id' => 'questions#edit'
  get 'questions/new/:survey_id' => 'questions#new'
  resources :questions

  get 'survey/:survey_id/send_notification' => 'courses#send_notification', as: 'send_notification'
  get 'results_by_group/:course_id/:survey_name/:group_name' => 'surveys#results_by_group', as: 'results_by_group'
  get 'results_by_user/:survey_id' => 'surveys#results_by_user', as: 'results_by_user'
  get 'my_surveys/:id/results/:course_id/:survey_name/:evaluated_user_id/:user_id' => 'surveys#results', as: 'survey_results'
  post 'save_survey_answers' => 'surveys#save_survey_answers'
  get 'survey/:id/answer' => 'surveys#answer_survey', as: 'answer_survey'
  get 'my_surveys/pending' => 'surveys#my_pending_surveys', as: 'my_pending_surveys'
  get 'my_surveys' => 'surveys#my_surveys'
  get 'surveys/:id/preview' => 'surveys#preview', as: 'survey_preview'
  resources :surveys
  
  post 'courses/check_students_list' => 'courses#check_students_list', as: 'check_students_list'
  get 'couses/:course_id/results/:survey_name/group/:group_name' => 'courses#survey_results_by_group', as: 'survey_group_results'
  post 'update_assigned_survey' => 'courses#update_assigned_survey'
  get 'courses/:course_id/edit_assigned_survey/:survey_id' => 'courses#edit_assigned_survey', as: 'edit_assigned_survey'
  get 'courses/:course_id/assigned_survey/:survey_name' => 'courses#assigned_survey_details', as: 'assigned_survey_details'
  post 'save_assigned_survey' => 'courses#save_assigned_survey'
  get 'course/:id/assign_survey' => 'courses#assign_survey', as: 'assign_survey'
  post 'assign_student_to_course' => 'courses#assign_student_to_course'
  post 'remove_student_from_course' => 'courses#remove_student_from_course'
  get 'courses/:id/assign_students' => 'courses#assign_students', as: 'assign_students'
  resources :courses
  
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit_user'
  patch 'users/:id/edit' => 'users#update_user'
  delete 'user/:id' => 'users#destroy'
  get 'new_user' => 'users#new_user'
  post 'users/create_user' => 'users#create_user'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  devise_for :users
  get 'dashboard/index'

   root 'dashboard#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	has_many :questions
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :preview]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.paginate(page: params[:page], per_page: 30).order('created_at DESC')
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to surveys_url, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
  end

  def my_surveys
    if current_user.student?
      @assigned_surveys = AssignedSurvey.select(:id, :name, :course_id, :answered, :evaluated_user_id, :survey_id, :user_id)
                                        .where(user_id: current_user.id)
    else
      @assigned_surveys = AssignedSurvey.joins(:course)
                                        .select(:id, :name, :course_id, :answered, :evaluated_user_id, :survey_id, :user_id)
                                        .where(courses: {user_id: current_user.id})
                                        .paginate(page: params[:page], per_page: 7)
                                        .order('assigned_surveys.created_at DESC')
    end
  end

  def my_pending_surveys
    @pending_surveys = AssignedSurvey.select(:id, :name, :course_id, :answered, :evaluated_user_id)
                                      .where(user_id: current_user.id, answered: false)
  end

  def answer_survey
    @assigned_survey = AssignedSurvey.find(params[:id])
  end

  def save_survey_answers
    params[:answers].to_a.each do |answer|
      SurveyResult.create(assigned_survey_id: params[:assigned_survey], answer_option_id: answer[1])
    end
    AssignedSurvey.find(params[:assigned_survey]).update(answered: true)
    respond_to do |format|
      format.html {redirect_to my_surveys_path, notice: 'Encuesta contestada con éxito'}
    end
  end

  def results
    @survey = AssignedSurvey.find_by(user_id: params[:user_id], 
                                     survey_id: params[:id], 
                                     course_id: params[:course_id],
                                     evaluated_user_id: params[:evaluated_user_id],
                                     name: params[:survey_name])
  end

  def results_by_user
    survey = AssignedSurvey.find(params[:survey_id])
    results = SurveyResult.select(:answer_option_id)
                          .where(assigned_survey_id: survey.id)
    labels = []
    data = []
    results.each_with_index do |result, index|
      labels << 'Pregunta '+(index+1).to_s
      data << result.answer_option.score
    end
    response = {
      'labels': labels,
      'datasets': [
        {
          'label': survey.evaluated_user.full_name,
          'data': data,
          'backgroundColor': 'rgba(0, 167, 208, 0.5)',
          'borderColor': 'rgba(0, 167, 208, 1)',
          'pointBorderColor': '#FFF',
          'pointHoverBackgroundColor': '#FFF',
          'pointHoverBorderColor': 'rgba(0, 167, 208, 1)'
        }
      ]
    }
    respond_to do |format|
      format.html {render json: response.to_json }
    end
  end

  def results_by_group
    students = CourseStudent.where(group_name: params[:group_name], course_id: params[:course_id])
                            .pluck(:user_id)
    surveys = AssignedSurvey.where(course_id: params[:course_id],
                                    name: params[:survey_name],
                                    user_id: students,
                                    answered: true)
    labels = []
    datasets = []
    surveys.first.survey_results.each_with_index do |result, index|
      labels << 'Pregunta '+(index+1).to_s
    end
    colors = default_colors

    #Resultado promedio
    require 'matrix'

    average = Vector.elements(Array.new(labels.count, 0.0))
    students_average = Hash.new
    surveys.each_with_index do |survey, index|
      data = Vector.elements(survey.survey_results.map{|result| result.answer_option.score.to_f})
      if students_average[survey.evaluated_user_id].nil?
        students_average[survey.evaluated_user_id] = Hash.new
        students_average[survey.evaluated_user_id][:data] = data
        students_average[survey.evaluated_user_id][:count] = 1
        students_average[survey.evaluated_user_id][:student] = survey.evaluated_user.full_name
      else
        students_average[survey.evaluated_user_id][:data] += data
        students_average[survey.evaluated_user_id][:count] += 1
      end
      average += data
    end
    students_average.each_with_index do |student_average, index|
      datasets << {
        'label': student_average[1][:student],
        'data': student_average[1][:data] / student_average[1][:count],
        'backgroundColor': 'rgba(0,0,0,0)',#colors[index%colors.count][:background],
        'borderColor': colors[index%colors.count][:border],
        'pointBorderColor': '#FFF',
        'pointHoverBackgroundColor': '#FFF',
        'pointHoverBorderColor': colors[index%colors.count][:border],
        'pointStyle': colors[index%colors.count][:pointer]
      }
    end
    surveys_count = surveys.count
    datasets << {
                'label': 'Promedio del grupo',
                'data': average / surveys_count,
                'backgroundColor': colors[surveys_count%colors.count][:background],
                'borderColor': colors[surveys_count%colors.count][:border],
                'pointBorderColor': '#FFF',
                'pointHoverBackgroundColor': '#FFF',
                'pointHoverBorderColor': colors[surveys_count%colors.count][:border]
              }

    respond_to do |format|
      format.html {render json: {'labels': labels, 'datasets': datasets}.to_json }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description)
    end

    def default_colors
      return [
        {
          background: 'rgba(244, 67, 54, 0.5)',
          border: 'rgba(244, 67, 54, 1)',
          pointer: 'triangle'
        },
        {
          background: 'rgba(255, 152, 0, 0.5)',
          border: 'rgba(255, 152, 0, 1)',
          pointer: 'cross'
        },
        {
          background: 'rgba(41, 182, 246, 0.5)',
          border: 'rgba(41, 182, 246, 1)',
          pointer: 'star'
        },
        {
          background: 'rgba(156, 39, 176, 0.5)',
          border: 'rgba(156, 39, 176, 1)',
          pointer: 'rect'
        },
        {
          background: 'rgba(33, 150, 243, 0.5)',
          border: 'rgba(33, 150, 243, 1)',
          pointer: 'line'
        },
        {
          background: 'rgba(0, 137, 123, 0.5)',
          border: 'rgba(0, 137, 123, 1)',
          pointer: 'dash'
        },
        {
          background: 'rgba(139, 195, 74, 0.5)',
          border: 'rgba(139, 195, 74, 1)',
          pointer: 'rectRounded'
        },
        {
          background: 'rgba(205, 220, 57, 0.5)',
          border: 'rgba(205, 220, 57, 1)',
          pointer: 'rectRot'
        },
        {
          background: 'rgba(255, 64, 129, 0.5)',
          border: 'rgba(255, 64, 129, 1)',
          pointer: 'crossRot'
        },
        {
          background: 'rgba(255, 255, 0, 0.5)',
          border: 'rgba(255, 255, 0, 1)',
          pointer: 'circle'
        }
      ]
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_questions.html.erb
<% questions.each do |question| %>
	<div class="box collapsed-box">
		<div class="box-header with-border row">
			<div class="col-xs-12 col-md-7">
				<h3 class="box-title question-title">
					<%= question.statement %>
						<span class="label label-success">  <%= question.score %> Puntos</span>	
				</h3>
			</div>
			<div class="col-xs-12 col-md-5">
				<div class="pull-right">
					<% unless @survey.nil? %>
						<%= link_to 'Editar', edit_question_path(question)+'/'+@survey.id.to_s, class: 'btn btn-primary btn-flat' %>
					<% end %>
					<button class="btn btn-primary btn-flat" data-widget="collapse">
						Ver opciones (<%= question.answer_options.count %>)
					</button>
				</div>
			</div>
			<div class="col-xs-12"><%= question.hint %></div>
		</div>
		<div class="box-body">
			<% unless question.answer_options.empty? %> 
				<table class="table">
					<thead>
						<th>#</th>
						<th>Respuesta</th>
						<th>Puntaje</th>
					</thead>
					<tbody>
						<% count = 1 %>
						<% question.answer_options.each do |answer| %>
							<tr>
								<td><%= count %></td>
								<td><%= answer.answer %></td>
								<td><%= answer.score %></td>
							</tr>
							<% count += 1 %>
						<% end %>
					</tbody>
				</table>
				<ol>
				</ol>
			<% else %>
				<p>Esta pregunta no tiene opciones de respuesta asignadas</p>
			<% end %>
		</div>
	</div>
<% end %>

app/views/surveys/_student_surveys.html.erb
<div class="table-responsive">
	<table class="table">
		<thead>
			<th>Encuesta</th>
			<% if show_course %>
				<th class="hidden-xs">Asignatura (Semestre/Año)</th>
			<% end %>
			<th>Evalúa a</th>
			<th>Estado</th>
			<th></th>
		</thead>
		<tbody>
			<% assigned_surveys.each do |survey| %>
				<tr>
					<td><%= survey.name %></td>
					<% if show_course %>
						<td class="hidden-xs"><%= survey.course.name %> (<%= survey.course.sem_year %>)</td>
	        <% end %>
	        <td><%= survey.evaluated_user.nil? ? '' : survey.evaluated_user.full_name %></td>
	        <% if survey.answered %>
	          <td class="text-green"><i class="fa fa-check"></i> Contestada</td>
	          <td><%= link_to 'Ver respuestas', survey_results_path(survey.survey_id, survey.course_id, survey.name, survey.evaluated_user_id, current_user.id), class: 'btn btn-success btn-flat' %></td>
	        <% else %>
	          <td class="text-yellow"><i class="fa fa-exclamation-triangle"></i> Pendiente</td>
						<td><%= link_to 'Contestar', answer_survey_path(survey,), class: 'btn btn-warning btn-flat' %></td>
	        <% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/surveys/_teacher_surveys.html.erb
<div class="table-responsive">
	<table class="table">
		<thead>
			<th>Encuesta</th>
			<% if show_course %>
				<th class="hidden-xs">Asignatura (Semestre/Año)</th>
			<% end %>
			<th>Responsable</th>
			<th>Evalúa a</th>
			<th></th>
			<th></th>
			<th>Estado</th>
		</thead>
		<tbody>
			<% assigned_surveys.each do |survey| %>
				<tr>
					<td><%= survey.name %></td>
					<% if show_course %>
						<td class="hidden-xs"><%= survey.course.name %> (<%= survey.course.sem_year %>)</td>
	        <% end %>
	        <td><%= survey.user.full_name %></td>
	        <td><%= survey.evaluated_user.nil? ? '' : survey.evaluated_user.full_name %></td>
	        <td><%= link_to 'Ver detalles', assigned_survey_details_path(survey.course_id, survey.name) %></td>
	        <td><%= link_to 'Editar', edit_assigned_survey_path(survey.course_id, survey.id) %></td>
	        <% if survey.answered %>
	          <td><%= link_to 'Ver respuestas', survey_results_path(survey.survey_id, survey.course_id, survey.name, survey.evaluated_user_id, survey.user_id), class: 'btn btn-success btn-flat' %></td>
	        <% else %>
	          <td>
	          	<%= link_to '#', class: 'btn btn-warning btn-flat' do %>
		            <i class="fa fa-paper-plane"></i> Enviar recordatorio
		          <% end %>    
	          </td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= will_paginate assigned_surveys, param_name: 'page', renderer: BootstrapPagination::Rails %>
</div>

app/views/surveys/answer_survey.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Contestar encuesta pendiente
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= my_surveys_path %>"></a>Mis encuestas</li>
    <li class="active">Contestar encuesta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">
      <%= link_to my_surveys_path do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-xs-12 col-md-8 col-md-offset-2">
			<div class="panel">
				<div class="panel-body">
					<h2><%= @assigned_survey.name %></h2>
					<p><%= @assigned_survey.survey.description %></p>
					<div class="callout callout-primary">
						<h4>Estas evaluando a <b><%= @assigned_survey.evaluated_user.full_name %></b></h4>
					</div>
					<% unless @assigned_survey.survey.questions.empty? %>
						<%= form_tag save_survey_answers_path do %>
							<% @assigned_survey.survey.questions.each_with_index do |question, index| %>
								<div class="question">
									<h4><%= question.statement %></h4>
									<p><%= question.hint %></p>
									<div class="answers-options">
										<% question.answer_options.each do |answer| %>
											<div class="answer form-group">
												<label>
													<%= radio_button_tag '[answers]question'+index.to_s, answer.id, false, required: true %>
													<%= answer.answer %>
												</label>
											</div>
										<% end %>
									</div>	
								</div>
							<% end %>
							<%= hidden_field_tag :assigned_survey, @assigned_survey.id %>
							<%= submit_tag 'Enviar respuesta', class: 'btn btn-primary btn-flat btn-block' %>
						<% end %>
					<% else %>
						<p>Esta encuesta no tiene preguntas asociadas</p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/surveys/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Editar Plantilla de Encuestas
  </h1>
  <ol class="breadcrumb">
  	<li><a href="<%= survey_path(@survey) %>">Plantilla de Encuesta</a></li>
    <li class="active">Editar Plantilla de Encuesta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">
  	<div class="col-xs-12">
  		<%= link_to survey_path(@survey)  do %>
  			<i class="fa fa-arrow-left"></i> Volver
  		<% end %>
  	</div>
	</div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
    	<div class="box box-primary">
    		<div class="box-header with-border">
    			<h3 class="box-title">Editar pregunta</h3>
    		</div>
	    	<div class="box-body">
					<%= render 'form' %>
	    	</div>
    	</div>
    </div>
  </div>
</section>
<!-- /.content -->

app/views/surveys/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Plantillas de Encuesta
    <small>Listado de Plantillas de Encuesta registradas</small>
  </h1>
  <ol class="breadcrumb">
    <li class="active">Plantillas de Encuesta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to root_path  do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @surveys.each_with_index do |survey, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= survey.name %></td>
                  <td><%= survey.description %></td>
                  <td><%= link_to 'Ver', survey %></td>
                  <!-- <td><%#= link_to 'Eliminar', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                </tr>
              <% end %>
            </tbody>
          </table>      
          <%= will_paginate @surveys, param_name: 'page', renderer: BootstrapPagination::Rails %>
          <%= link_to 'Nueva encuesta', new_survey_path, class: 'btn btn-primary btn-flat' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /.content -->

app/views/surveys/my_pending_surveys.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Mis encuestas pendientes
    <small>Ver todas mis encuestas pendientes</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= my_surveys_path %>"></a>Mis encuestas</li>
    <li class="active">Mis encuestas pendientes</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">
    <div class="col-xs-12">
      <%= link_to my_surveys_path do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
    </div>
  </div>
  <br>
  <div class="row">
  	<div class="col-xs-12">
  		<div class="box box-primary">
  			<div class="box-header">
  				<h3 class="box-title">Mis encuestas pendientes</h3>
  			</div>
  			<div class="box-body">
  				<table class="table">
  					<thead>
  						<th>Encuesta</th>
              <th class="hidden-xs">Asignatura (Semestre/Año)</th>
              <th>Evalúa a</th>
  						<th></th>
  					</thead>
  					<tbody>
  						<% @pending_surveys.each do |survey| %>
  							<tr>
  								<td><%= survey.name %></td>
  								<td class="hidden-xs"><%= survey.course.name %> (<%= survey.course.sem_year %>)</td>
  								<td><%= survey.evaluated_user.nil? ? '' : survey.evaluated_user.full_name %></td>
  								<td><%= link_to 'Contestar', answer_survey_path(survey), class: 'btn btn-warning btn-flat' %></td>
                </tr>
  						<% end %>
  					</tbody>
  				</table>
  			</div>
  		</div>
  	</div>	
  </div>
</section>

app/views/surveys/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Nueva encuesta
    <small>Cree un nueva encuesta</small>
  </h1>
  <ol class="breadcrumb">
  	<li><a href="<%= surveys_path %>">Encuestas</a></li>
    <li class="active">Nueva encuesta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
  	<div class="col-xs-12">
  		<%= link_to surveys_path  do %>
  			<i class="fa fa-arrow-left"></i> Volver
  		<% end %>
  	</div>
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
					<%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /.content -->

app/views/surveys/preview.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Previsualización de una encuesta
    <small>Previsualice como será el despliegue de un encuesta</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= surveys_path %>">Encuestas</a></li>
    <li><a href="<%= survey_path @survey %>">Ver encuesta</a></li>
    <li class="active">Previsualización</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<%= link_to survey_path @survey do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
		</div>
	</div>
  <br>
	<div class="row">
		<div class="col-xs-12 col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-body">
					<h2><%= @survey.name %></h2>
					<div>
						<%= @survey.description %>
					</div>
					<% unless @survey.questions.empty? %>
						<% @survey.questions.each_with_index do |question, index| %>
							<div class="question">
								<h4><%= question.statement %></h4>
								<p><%= question.hint %></p>
								<div class="answers-options">
									<% question.answer_options.each do |answer| %>
										<div class="answer">
											<%= radio_button_tag 'question'+index.to_s, answer.score %>
											<%= label_tag answer.score.to_s, answer.answer %>
										</div>
									<% end %>
								</div>	
							</div>
						<% end %>
					<% else %>
						<p>Esta encuesta no tiene preguntas asociadas</p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/surveys/results.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Ver respuestas de la encuesta "<%= @survey.name %>"
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= my_surveys_path %>">Mis encuestas</a></li>
    <li class="active">Resultados de <%= @survey.name %></li>
  </ol>
</section>

<section class="content">
	<div class="row">
    <div class="col-xs-12">
      <%= link_to :back do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
    </div>
  </div>
  <br>
  <%= render 'survey_result', survey: @survey %>
</section>

<script>
	$(document).ready(function(){
		var ctx = document.getElementById('chart').getContext('2d');
    $.get('<%= results_by_user_path(@survey.id) %>')
      .done(function(data){
    		var myRadarChart = new Chart(ctx, {
    	    type: 'radar',
    	    data: JSON.parse(data),
    	    options: {
                    scale: {
                      ticks: {
                        beginAtZero: true,
                        min: 0,
                        max: 5,
                        stepSize: 1
                      }
                    } 

                  }
    		});
      });
	});
</script>

app/views/surveys/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Ver encuesta
    <small>Ver toda la información de un encuesta</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= surveys_path %>">Encuestas</a></li>
    <li class="active">Ver encuesta</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to surveys_path do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
      <div class="pull-right">
        <a href="<%= survey_preview_path(@survey) %>" class="btn btn-primary btn-flat btn-lg"><i class="fa fa-eye"></i> Previsualizar encuesta</a>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">Información general</h3>
          <div class="box-tools pull-right">
            <%= link_to 'Editar', edit_survey_path(@survey), class: 'btn btn-primary btn-flat' %> 
          </div>
        </div>
        <div class="box-body">
          <table class="table">
            <tbody>
              <tr>
                <th>Nombre</th>
                <td><%= @survey.name %></td>
              </tr>
              <tr>
                <th>Descripción</th>
                <td><%= @survey.description %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-8">
      <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">Preguntas</h3>
          <div class="box-tools pull-right">
            <%= link_to new_question_path+'/'+@survey.id.to_s, class: 'btn btn-primary btn-flat' do %>
            	<i class="fa fa-plus"></i> Agregar pregunta
            <% end %>
          </div>
        </div>
        <div class="box-body">
        	<% unless @survey.questions.empty? %>
            <%= render 'questions', questions: @survey.questions %>
        	<% else %>
        		<p>Esta encuesta no tiene preguntas asociadas</p>
        	<% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /.content -->