config/routes.rb
Rails.application.routes.draw do

  post 'add_answer_option_ajax' => 'answer_options#add_answer_option_ajax'
  resources :answer_options

  post 'questions_by_survey' => 'questions#find_by_survey'
  get 'questions/:id/edit/:survey_id' => 'questions#edit'
  get 'questions/new/:survey_id' => 'questions#new'
  resources :questions

  get 'survey/:survey_id/send_notification' => 'courses#send_notification', as: 'send_notification'
  get 'results_by_group/:course_id/:survey_name/:group_name' => 'surveys#results_by_group', as: 'results_by_group'
  get 'results_by_user/:survey_id' => 'surveys#results_by_user', as: 'results_by_user'
  get 'my_surveys/:id/results/:course_id/:survey_name/:evaluated_user_id/:user_id' => 'surveys#results', as: 'survey_results'
  post 'save_survey_answers' => 'surveys#save_survey_answers'
  get 'survey/:id/answer' => 'surveys#answer_survey', as: 'answer_survey'
  get 'my_surveys/pending' => 'surveys#my_pending_surveys', as: 'my_pending_surveys'
  get 'my_surveys' => 'surveys#my_surveys'
  get 'surveys/:id/preview' => 'surveys#preview', as: 'survey_preview'
  resources :surveys
  
  post 'courses/check_students_list' => 'courses#check_students_list', as: 'check_students_list'
  get 'couses/:course_id/results/:survey_name/group/:group_name' => 'courses#survey_results_by_group', as: 'survey_group_results'
  post 'update_assigned_survey' => 'courses#update_assigned_survey'
  get 'courses/:course_id/edit_assigned_survey/:survey_id' => 'courses#edit_assigned_survey', as: 'edit_assigned_survey'
  get 'courses/:course_id/assigned_survey/:survey_name' => 'courses#assigned_survey_details', as: 'assigned_survey_details'
  post 'save_assigned_survey' => 'courses#save_assigned_survey'
  get 'course/:id/assign_survey' => 'courses#assign_survey', as: 'assign_survey'
  post 'assign_student_to_course' => 'courses#assign_student_to_course'
  post 'remove_student_from_course' => 'courses#remove_student_from_course'
  get 'courses/:id/assign_students' => 'courses#assign_students', as: 'assign_students'
  resources :courses
  
  get 'users' => 'users#index'
  get 'user/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit_user'
  patch 'users/:id/edit' => 'users#update_user'
  delete 'user/:id' => 'users#destroy'
  get 'new_user' => 'users#new_user'
  post 'users/create_user' => 'users#create_user'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  devise_for :users
  get 'dashboard/index'

   root 'dashboard#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :assign_students, :assign_survey]

  # GET /courses
  # GET /courses.json
  def index
    if current_user.admin?
      @courses = Course.paginate(page: params[:page], per_page: 30).order('created_at DESC')
    elsif current_user.teacher?
      @courses = Course.where(user_id: current_user.id)
                       .paginate(page: params[:page], per_page: 30)
                       .order('created_at DESC')
    else
      @courses = Course.joins(:course_students)
                       .where('course_students.user_id' => current_user.id)
                       .paginate(page: params[:page], per_page: 30)
                       .order('created_at DESC')
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @students = CourseStudent.where(course_id: @course.id).pluck(:user_id, :role, :group_name).map{|student| {name: User.find(student[0]).full_name, role: student[1], group_name: student[2]} }
    puts '---------'+@students.inspect
    @color = ["info", "danger", "default", "success", "primary", "warning"]
    surveys = AssignedSurvey.select(:name, :survey_id)
                            .where(course_id: params[:id])
                            .group(:name, :survey_id)
    @assigned_surveys = []
    unless current_user.student? and not current_user.project_leader?(@course.id)
      surveys.each do |survey|
        answered = AssignedSurvey.where(answered: true, name: survey.name).count
        pending = AssignedSurvey.where(answered: false, name: survey.name).count
        @assigned_surveys << {#id: survey[:survey_id], #survey.id,
                              name: survey.name, 
                              template: survey.survey.name, 
                              percentage: (answered.to_f/(answered + pending).to_f)*100}
      end
    else
      @assigned_surveys = AssignedSurvey.select(:id, :name, :course_id, :answered, :evaluated_user_id, :survey_id)
                                        .where(user_id: current_user.id, course_id: @course.id)

    end
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_url, notice: 'Curso creado satisfactoriamente' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Curso editado satisfactoriamente' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.update(status: !@course.status)
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Curso '+(@course.status ? 'activado' : 'desactivado')+' satisfactoriamente' }
      format.json { head :no_content }
    end
  end

  def assign_students
    @assigned_students = CourseStudent.where(course_id: @course.id).pluck(:user_id).map{|student| User.find(student) }
    @unassigned_students = User.where(roles_id: 3) - @assigned_students
    @groups = CourseStudent.where(course_id: @course.id)
                           .where.not(group_name: nil)
                           .pluck(:user_id, :role, :group_name)
                           .map{|student| {
                                id: student[0], 
                                email: User.find(student[0]).email, 
                                role: student[1], 
                                group_name: student[2]
                              } 
                            }
                           .group_by{|group| group[:group_name] }.sort
    @assigned_students = CourseStudent.where(course_id: @course.id, group_name: nil)
                                      .pluck(:user_id, :role, :group_name)
                                      .map{|student| {
                                        id: student[0], 
                                        email: User.find(student[0]).email, 
                                        role: student[1], 
                                        group_name: student[2]
                                        } 
                                      }
                                      .group_by{|group| group[:group_name] }
  end

  def assign_student_to_course    
    assign = CourseStudent.find_by(course_id: params[:course_id], user_id: params[:student_id])
    respond_to do |format|
      if assign.nil?
        format.html {render json: CourseStudent.create(course_id: params[:course_id], 
                                                       user_id: params[:student_id], 
                                                       role: params[:role], 
                                                       group_name: params[:group_name])}
      else
        format.html{render json: assign.update(role: params[:role], group_name: params[:group_name])}
      end
    end
  end

  def remove_student_from_course
    respond_to do |format|
      format.html {render json: CourseStudent.find_by(course_id: params[:course_id], user_id: params[:student_id]).destroy}
    end
  end

  def check_students_list
    students = params[:students_list].split(', ')
    unassigned = []
    not_created = []
    assigned = []
    students.each do |student|
      if user = User.find_by(email: student)
        if CourseStudent.find_by(user: user, course_id: params[:course_id]).nil?
          unassigned << user
        else
          assigned << student
        end
      else
        not_created << student
      end
    end
    respond_to do |format|
      format.html{render json: {unassigned: unassigned, assigned: assigned, not_created: not_created}}
    end
  end

  def assign_survey
    @surveys = Survey.all.map{|survey| [survey.name, survey.id]}
  end

  def save_assigned_survey
    groups = CourseStudent.select(:user_id, :group_name)
                           .where(course_id: params[:course_id])
                           .where.not(group_name: nil)
                           .group_by{|student| student.group_name }
                           .sort
                           .to_h
    students = CourseStudent.select(:user_id, :group_name).where(course_id: params[:course_id]).where.not(role: 'Ayudante')
    students.each do |student|
      unless student.group_name.nil?
        groups[student.group_name].each do |evaluate_user|
          AssignedSurvey.create(
                        survey_id: params[:survey_id],
                        user_id: student.user_id,
                        evaluated_user_id: evaluate_user.user_id,
                        course_id: params[:course_id],
                        name: params[:name],
                        answered: false)
        end
      end
    end
    respond_to do |format|
      format.html {redirect_to course_path(params[:course_id]), notice: 'Encuesta asignada con éxito'}
    end
  end

  def assigned_survey_details
    @course = Course.find(params[:course_id])
    surveys = AssignedSurvey.select(:id, :answered, :user_id, :evaluated_user_id, :survey_id)
                                     .where(course_id: params[:course_id], name: params[:survey_name])
    @assigned_survey = []
    surveys.each do |survey|
      @assigned_survey << {student: survey.user.full_name,
                           evaluated: survey.evaluated_user.nil? ? '' : survey.evaluated_user.full_name, 
                           answered: survey.answered, 
                           group: CourseStudent.find_by(course_id: @course.id, user_id: survey.user_id).group_name,
                           survey_id: survey.survey_id,
                           evaluated_user_id: survey.evaluated_user_id,
                           assigned_survey: survey.id
                         }
    end
    groups = @assigned_survey.group_by{|survey| survey[:group]}.to_a
    @assigned_survey = @assigned_survey.paginate(page: params[:page], per_page: 5)
    @groups_percentage = []
    groups.each do |group|
      answered = 0
      pending = 0
      group[1].each do |student|
        if student[:answered]
          answered += 1
        else
          pending += 1
        end
      end
      @groups_percentage << {name: group[0], percentage: (answered.to_f/(answered+pending).to_f)*100}
    end

    ##Cálculo de los módulos resultados por estudiante
    require 'matrix'
    surveys = AssignedSurvey.where(name: params[:survey_name], course_id: params[:course_id], answered: true)
    students_average = Hash.new
    module_results = Hash.new
    average = Hash.new

    surveys.each_with_index do |survey, index|
      data = Vector.elements(survey.survey_results.map{|result| result.answer_option.score.to_f})
      if students_average[survey.evaluated_user_id].nil?
        students_average[survey.evaluated_user_id] = Hash.new
        students_average[survey.evaluated_user_id][:data] = data
        students_average[survey.evaluated_user_id][:count] = 1
        students_average[survey.evaluated_user_id][:group] = CourseStudent.find_by(course_id: @course.id, 
                                                                                   user_id: survey.user_id)
                                                                          .group_name
        students_average[survey.evaluated_user_id][:module] = 0

app/helpers/courses_helper.rb
module CoursesHelper
	def get_role_class(role)
		case role
			when ''
				return 'btn-default'
			when nil
				return 'btn-default'
			when 'ayudante'
				return 'btn-primary'
			when 'jefe de grupo'
				return 'btn-success'
			when 'jefe de proyecto'
				return 'btn-warning'
		end
	end

	def new_survey_disabled(course)
		if course.can_create_survey?
			return ''
		else
			return 'disabled'
		end
	end
end

app/views/courses/assign_students.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Ver curso
    <small>Ver toda la información de un curso</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= courses_path %>">Cursos</a></li>
    <li><a href="<%= course_path(@course) %>"><%= @course.name %></a></li>
    <li class="active">Asignar estudiantes</li>
  </ol>
  <%= link_to course_path(@course) do %>
    <i class="fa fa-arrow-left"></i> Volver
  <% end %>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
    </div>
  </div>
  <div class="row">
    <br>
    <div class="col-xs-12 col-md-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Estudiantes registrados</h3>
          <p>Haga click sobre los estudiantes que desea asignar al curso</p>
        </div>
        <div class="box-body" id="available-students">
          <div id="assigned-alert" class="alert alert-dismissible alert-info hidden">
            <button class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <b>Los siguientes usuarios ya han sido asignados a un grupo:</b>
            <ul id="assigned-emails"></ul>
          </div>
          <div id="not-created-alert" class="alert alert-dismissible alert-warning hidden">
            <button class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <b>Los siguientes usuarios no están registrados en MANUEL:</b>
            <ul id="not-created-emails"></ul>
          </div>
          <div class="form-group" id="students-input">
            <%= label_tag :students_list, 'Ingrese los correos de los estudiantes separados por comas' %>
            <%= text_area_tag :students_list, '', class: 'form-control', id: 'students-list' %><br>
            <button id="upload-students" class="btn btn-primary btn-flat btn-block">Cargar estudiantes</button>
          </div>
        </div>
        <div class="box-footer">
          <i class="fa fa-info-circle primary"></i> Click derecho para asignar como ayudante
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">Estudiantes asignados</h3>
          <p>Haga click sobre los estudiantes que desea quitar del curso</p>
          <div class="box-tools pull-right">
            <button id='add-group' class="btn btn-primary btn-flat"><i class="fa fa-plus"></i> Agregar grupo</button>
          </div>
        </div>
        <div id="unassigned-students">          
          <% unless @assigned_students[nil].nil? %>
            <% @assigned_students[nil].each do |student| %>
              <span id="student<%= student[:id] %>" class="btn <%= get_role_class(student[:role]) %> student-button" onclick="removeStudent(<%= student[:id] %>, <%= @course.id %>, null)" draggable="true" ondragstart="drag_start(event)"><%= student[:email] %></span>
            <% end %>
          <% end %>
        </div>
        <div class="box-body" id="assigned-students">          
          <% @groups.each do |group| %>
            <div class="box box-group">
              <div class="box-header with-border">
                <h3 class="box-title">Grupo <%= group[0] %></h3>
                <div class="box-tools pull-right">
                  <span class="btn btn-danger btn-flat" onclick="removeGroup(<%= group[0] %>)"><i class="fa fa-times"></i> Eliminar grupo</span>
                </div>
              </div>
              <div class="box-body" group="<%= group[0] %>" id="group<%= group[0] %>" ondrop="drop(event)"  ondragover="allowDrop(event)">
                <% group[1].each do |student| %>
                  <span id="student<%= student[:id] %>" class="btn <%= get_role_class(student[:role]) %> student-button" onclick="removeStudent(<%= student[:id] %>, <%= @course.id %>, null)" draggable="true" ondragstart="drag_start(event)"><%= student[:email] %></span>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="box-footer">
          <i class="fa fa-info-circle primary"></i> 
          <span class="label label-primary">Ayudante</span>
          <span class="label label-success">Jefe de Grupo</span>
          <span class="label label-warning">Jefe de Proyecto</span>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /.content -->

<script>
  $('#upload-students').click(function(){
    $.post('<%= check_students_list_path %>', 
            {
              students_list: $('#students-list').val(), 
              course_id: <%= @course.id %>
          })
        .done(function(data){
          $('#students-input').remove();
          var data = JSON.parse(data);
          data.unassigned.forEach(function(student){
            $('#available-students').append(
                '<span id="student'+student.id+'" class="btn btn-default student-button" onclick="assignStudent('+student.id+', <%= @course.id %>, null)" draggable="true" ondragstart="drag_start(event)">'+ student.email +'</span>'
              )
          });
          if (data.assigned.length > 0) {
            data.assigned.forEach(function(student){
              $('#assigned-emails').append('<li>'+student+'</li>')
            });
            $('#assigned-alert').removeClass('hidden');
          }
          if (data.not_created.length > 0) {
            data.not_created.forEach(function(student){
              $('#not-created-emails').append('<li>'+student+'</li>')
            });
            $('#not-created-alert').removeClass('hidden');
          }
        });
  });

  function allowDrop(ev) {
    ev.preventDefault();
  }

  function drag_start(ev) {
    var args = ev.target.getAttribute('onclick').split('(')[1].split(',');
    ev.dataTransfer.setData("id", ev.target.id);
    ev.dataTransfer.setData("student_id", args[0]);
    ev.dataTransfer.setData("course_id", args[1]);
  }

  function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("id");
    var student = document.getElementById(data);
    student.className = 'btn btn-default student-button';
    if (ev.target.tagName == 'BUTTON') {
      ev.target.parentElement.appendChild(student);
    }
    else{
      ev.target.appendChild(student);
    }
    $.post('<%= assign_student_to_course_path %>',
          {
            course_id: ev.dataTransfer.getData("course_id"),
            student_id: ev.dataTransfer.getData("student_id"),
            role: '',
            group_name: ev.target.getAttribute('group')
          })
          .done(function(data){            
            toastr['info']('Estudiante asignado con éxito');
          });
  }
  function assignStudent(student_id, course_id, role){
    $.post('<%= assign_student_to_course_path %>',
          {
            course_id: course_id,
            student_id: student_id,
            role: role
          })
          .done(function(data){
            if (role == 'ayudante') {
              $('#unassigned-students').append($('#student'+student_id).remove().attr('onclick', 'removeStudent('+student_id+','+course_id+', null)').removeClass('btn-default').addClass('btn-primary'));
            }
            else {
              $('#unassigned-students').append($('#student'+student_id).remove().attr('onclick', 'removeStudent('+student_id+','+course_id+', null)'));
            }
            toastr['info']('Estudiante asignado con éxito');
          });
  }

  function removeStudent(student_id, course_id, role){
    $.post('<%= remove_student_from_course_path %>',
          {
            course_id: course_id,
            student_id: student_id,
            role: role
          })
          .done(function(data){
            $('#available-students').append($('#student'+student_id).remove().attr('onclick', 'assignStudent('+student_id+','+course_id+', null)'));
            toastr['info']('Estudiante removido con éxito');
          });
  }

  $(function() {
    $.contextMenu({
      selector: '.student-button', 
      callback: function(key, options) {
        var args = $(this).attr('onclick').split('(')[1].split(',');
        if (key == 'assistant') {
          assignStudent(args[0], args[1], 'ayudante');
        }
        else if (key == 'group leader') {
          var new_leader = $(this);
          var group_name = new_leader.parent().attr('group');
          $.post('<%= assign_student_to_course_path %>',
            {
              course_id: args[1],
              student_id: args[0],
              role: 'jefe de grupo',
              group_name: group_name
            })
            .done(function(data){            
              removeOldGroupLeader(group_name);
              new_leader.removeClass('btn-default').addClass('btn-success');
              toastr['info']('Estudiante asignado como jefe de grupo con éxito');
            });
        }
        // Jefe de proyecto
        else {
          var new_leader = $(this);
          var group_name = new_leader.parent().attr('group');
          $.post('<%= assign_student_to_course_path %>',
            {
              course_id: args[1],
              student_id: args[0],
              role: 'jefe de proyecto'
            })
            .done(function(data){            
              removeOldProjectLeader();
              if ($(this).parent().attr('id') != 'unassigned-students') {
                $('#unassigned-students').append($('#student'+args[0]).remove().attr('onclick', 'removeStudent('+args[0]+','+args[1]+', null)').removeClass('btn-default').addClass('btn-warning'));
              }
              toastr['info']('Estudiante asignado como jefe de proyecto con éxito');
            });
        }
      },
      items: {
        "assistant": {name: "Asignar como ayudante"},
        "group leader": {name: "Asignar como jefe de grupo"},
        "project leader": {name: "Asignar como jefe de proyecto"}
      }
    });

  });

  function removeOldGroupLeader(group_name) {
    var old_leader = $('#group'+group_name).find('.btn-success');
    if (old_leader.length > 0) {
      var args = old_leader.attr('onclick').split('(')[1].split(',');
      $.post('<%= assign_student_to_course_path %>',
          {
            course_id: args[1],
            student_id: args[0],
            group_name: group_name,
            role: ''
          })
          .done(function(data){            
            old_leader.removeClass('btn-success').addClass('btn-default');
          });
    }
  }

  function removeOldProjectLeader() {
    var old_leader = $('#unassigned-students').find('.btn-warning');
    if (old_leader.length > 0) {
      var args = old_leader.attr('onclick').split('(')[1].split(',');
      $.post('<%= assign_student_to_course_path %>',
          {
            course_id: args[1],
            student_id: args[0],
            role: ''
          })
          .done(function(data){            
            old_leader.removeClass('btn-warning').addClass('btn-default');
          });
    }
  }

  $('#add-group').click(function(){
    var group_count = $('.box-group').length+1;
    $('#assigned-students').append(
            '<div class="box box-group">'+
              '<div class="box-header with-border">'+
                '<h3 class="box-title">Grupo '+group_count+'</h3>'+
                '<div class="box-tools pull-right">'+
                  '<button class="btn btn-danger btn-flat" onclick="removeGroup('+group_count+')"><i class="fa fa-times"></i> Eliminar grupo</button>'+
                '</div>'+
              '</div>'+
              '<div class="box-body group-students-container" group="'+group_count+'" id="group'+group_count+'" ondrop="drop(event)" ondragover="allowDrop(event)">'+
              '</div>'+
            '</div>'
            )
  });

  function removeGroup(group){
    var students = $('#group'+group).children();
    $('#group'+group).parent().remove();
    $('#unassigned-students').append(students);
    var success = true;
    students.each(function(){
      var args = $(this).attr('onclick').split('(')[1].split(',');
      $.post('<%= assign_student_to_course_path %>',
        {
          course_id: args[1],
          student_id: args[0]
        })
        .fail(function(){
          success = false;
        });
    });
    if (success) {
      toastr['info']('Grupo eliminado con éxito');
    }
  }
</script>

app/views/courses/assign_survey.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Asignar encuesta
    <small>Asignar una encuesta un curso</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= courses_path %>">Cursos</a></li>
    <li><a href="<%= course_path(@course) %>"><%= @course.name %></a></li>
    <li class="active">Asignar encuesta</li>
  </ol>
  <%= link_to course_path @course do %>
    <i class="fa fa-arrow-left"></i> Volver
  <% end %>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="callout callout-warning">
				<h4>¿Están correctamente conformados los grupos?</h4>
				<p>
					Esta encuesta se creará con los grupos que están conformados actualmente. <br>
					Cualquier modificación en los grupos no afectará a la encuesta que se está creando en estos momentos.
				</p>
				<%= link_to 'Ir a edición de grupos', assign_students_path(@course), class: 'btn btn-primary btn-flat' %>
			</div>
		</div>	
	</div>
	<br>
	<div class="row">
		<div class="col-xs-12 col-md-4">
			<div class="panel">
				<div class="panel-body">
					<h3>Asignar encuesta</h3>
					<%= render 'assign_survey_form', action_path: save_assigned_survey_path, action_button: 'Crear' %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-md-8">
			<div class="panel">
				<div class="panel-body">
					<h3>Preguntas de la encuesta</h3>
					<div id="survey-questions">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	$('#select-survey').change(function(){
		$('#survey-questions').empty();
		$.post('<%= questions_by_survey_path %>', {survey_id: $(this).val()});
	})
</script>

app/views/courses/assigned_survey_details.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Ver detalles de <%= params[:survey_name] %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= courses_path %>">Cursos</a></li>
    <li><a href="<%= course_path(@course) %>"><%= @course.name %></a></li>
    <li>Detalles de encuesta</li>
    <li class="active"><%= params[:survey_name] %></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-xs-12">
      <%= link_to course_path @course do %>
        <i class="fa fa-arrow-left"></i> Volver
      <% end %>
		</div>	
	</div>
	<br>
	<div class="row">
		<div class="col-xs-12">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title">Estado de la encuesta</h3>
				</div>
				<div class="box-body">
					<table class="table">
						<thead>
							<th>Estudiante</th>
							<th>Evalúa a</th>
							<th>Grupo</th>
							<th>Estado</th>
							<th></th>
						</thead>
						<tbody>
							<% @assigned_survey.each do |survey| %>
								<tr>
									<td><%= survey[:student] %></td>
									<td><%= survey[:evaluated] %></td>
									<td><%= survey[:group] %></td>
									<% if survey[:answered] %>
                    <td class="text-green"><i class="fa fa-check"></i> Contestada</td>
                    <td><%#= link_to 'Ver respuestas', survey_results_path(survey[:survey_id], @course.id, params[:survey_name], survey[:evaluated_user_id]), class: 'btn btn-success btn-flat' %></td>
                  <% else %>
                    <td class="text-yellow"><i class="fa fa-exclamation-triangle"></i> Pendiente</td>
  									<td>
  										<%= link_to send_notification_path(survey_id: survey[:assigned_survey]), class: 'btn btn-warning btn-flat btn-notify' do %>
  											<i class="fa fa-send"></i> Enviar recordatorio
  										<% end %>
  									</td>
                  <% end %>
								</tr>
							<% end %>
						</tbody>
					</table>
					<div class="paginate">
						<%= will_paginate @assigned_survey, renderer: BootstrapPagination::Rails %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-md-6">
			<div class="box box-success">
				<div class="box-header">
					<h3 class="box-title">Resultados</h3>
				</div>
				<div class="box-body">
					<div id="group-results">
						<div class="nav-tabs-custom">
							<ul class="nav nav-tabs">
								<% @group_result.size.times do |group| %>
									<li class="<%= group == 0 ? 'active' : nil %>">
										<a href="#tab<%= group %>" data-toggle="tab" aria-expanded="true">Grupo <%= group+1 %></a>
									</li>
								<% end %>
							</ul>
							<div class="tab-content">
								<% @group_result.size.times do |group| %>
									<div class="tab-pane <%= group == 0 ? 'active' : nil %>" id="tab<%= group %>">
										<table class="table table-result">
											<thead>
												<th>Estudiante</th>
												<th>Módulo</th>
											</thead>
											<tbody>
												<% @group_result[(group+1).to_s].each do |result| %>
													<tr>
														<td><%= result[:student] %></td>
														<td class="<%= result[:result] < 0 ? 'red' : 'green' %>"><%= result[:result].round(2) %></td>
													</tr>
												<% end %>
											</tbody>
										</table>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-md-6">
			<div class="box box-primary">
				<div class="box-header">
					<h3 class="box-title">Porcentaje de encuestas contestadas por grupo</h3>
				</div>
				<div class="box-body">
					<table class="table">
						<thead>
							<th>Grupo</th>
							<th>% Contestadas</th>
							<th></th>
						</thead>
						<tbody>
							<% @groups_percentage.each do |group| %>
								<tr>
									<td>Grupo <%= group[:name] %></td>
									<td><%= number_to_percentage(group[:percentage], strip_insignificant_zeros: true) %></td>
									<td>
										<% if group[:percentage] > 0 %>
											<%= link_to 'Ver resultados', survey_group_results_path(@course.id, params[:survey_name], group[:name]), class: 'btn btn-success btn-flat' %>
										<% end %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	$('.btn-notify').click(function(){
		console.log('sadfas');
		var parent = $(this).parent();
		$(this).hide();
		parent.text('Enviando notificación...');
	});
</script>